---
apiVersion: v1
kind: Namespace
metadata:
  name: custom-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-nginx-deployment
  namespace: custom-nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/jsanderson104/stuff:my-nginx
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: custom-image-svc
  namespace: custom-nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # Changed this from 9090 to port 80 since it's NGINX and it wouldn't make sense to put another nginx reverse proxy infront of this one. If i want SSL configure it in the image/container start and not over-complicate it with 2nginx instances.
      targetPort: 9090
